name: Shell Command

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "whatever"
      - name: echo another command
        run: |
          node -v
          npm -v
      - name: python script
        run: |
          import platform
          print(platform.processor())
          python -v
        shell: python

  run-win-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: WinPowerShell
        run: Get-Location
      - name: Get Win Dir
        run: pwd
        shell: bash


        
          
